name: EC2 pull

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # BranchをCheckout
      - name: Checkout
        uses: actions/checkout@v2

      # デプロイする
      - name: Deploy
        run: |

          # SSH接続して、git pullする 
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -l ${{ secrets.EC2_USER_NAME }} ${{ secrets.EC2_HOST_NAME }} "cd /home/ec2-user/tanzu-demo && git pull"
